package com.zhoufb.model.db;

import java.math.BigDecimal;
import java.util.Date;

public class ExportPayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.guid
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.app_type
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.app_time
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private Date appTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.app_status
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String appStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.app_uid
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String appUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.app_uname
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String appUname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.pay_code
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String payCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.pay_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.pay_type
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.pay_no
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String payNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.order_no
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.ebp_code
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String ebpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.ebp_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String ebpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.charge
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private BigDecimal charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.currency
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.note
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.return_status
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String returnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.return_time
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private Date returnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.return_info
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String returnInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.return_guid
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String returnGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.create_by
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.create_time
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.remark
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.lastupdate_by
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String lastupdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.lastupdate_date
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private Date lastupdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.created_by_company
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String createdByCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.update_by_company
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String updateByCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.ebc_code
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String ebcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.ebc_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String ebcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.created_by_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.created_company_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String createdCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.updated_by_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String updatedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.updated_company_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String updatedCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.enterprise_id
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.ciq_return_status
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String ciqReturnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_payment.ciq_return_info
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    private String ciqReturnInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.guid
     *
     * @return the value of t_export_payment.guid
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.guid
     *
     * @param guid the value for t_export_payment.guid
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.app_type
     *
     * @return the value of t_export_payment.app_type
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.app_type
     *
     * @param appType the value for t_export_payment.app_type
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setAppType(String appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.app_time
     *
     * @return the value of t_export_payment.app_time
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.app_time
     *
     * @param appTime the value for t_export_payment.app_time
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.app_status
     *
     * @return the value of t_export_payment.app_status
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.app_status
     *
     * @param appStatus the value for t_export_payment.app_status
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.app_uid
     *
     * @return the value of t_export_payment.app_uid
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getAppUid() {
        return appUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.app_uid
     *
     * @param appUid the value for t_export_payment.app_uid
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setAppUid(String appUid) {
        this.appUid = appUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.app_uname
     *
     * @return the value of t_export_payment.app_uname
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getAppUname() {
        return appUname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.app_uname
     *
     * @param appUname the value for t_export_payment.app_uname
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setAppUname(String appUname) {
        this.appUname = appUname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.pay_code
     *
     * @return the value of t_export_payment.pay_code
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.pay_code
     *
     * @param payCode the value for t_export_payment.pay_code
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.pay_name
     *
     * @return the value of t_export_payment.pay_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.pay_name
     *
     * @param payName the value for t_export_payment.pay_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setPayName(String payName) {
        this.payName = payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.pay_type
     *
     * @return the value of t_export_payment.pay_type
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.pay_type
     *
     * @param payType the value for t_export_payment.pay_type
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.pay_no
     *
     * @return the value of t_export_payment.pay_no
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.pay_no
     *
     * @param payNo the value for t_export_payment.pay_no
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.order_no
     *
     * @return the value of t_export_payment.order_no
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.order_no
     *
     * @param orderNo the value for t_export_payment.order_no
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.ebp_code
     *
     * @return the value of t_export_payment.ebp_code
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getEbpCode() {
        return ebpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.ebp_code
     *
     * @param ebpCode the value for t_export_payment.ebp_code
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setEbpCode(String ebpCode) {
        this.ebpCode = ebpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.ebp_name
     *
     * @return the value of t_export_payment.ebp_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getEbpName() {
        return ebpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.ebp_name
     *
     * @param ebpName the value for t_export_payment.ebp_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setEbpName(String ebpName) {
        this.ebpName = ebpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.charge
     *
     * @return the value of t_export_payment.charge
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public BigDecimal getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.charge
     *
     * @param charge the value for t_export_payment.charge
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setCharge(BigDecimal charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.currency
     *
     * @return the value of t_export_payment.currency
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.currency
     *
     * @param currency the value for t_export_payment.currency
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.note
     *
     * @return the value of t_export_payment.note
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.note
     *
     * @param note the value for t_export_payment.note
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.return_status
     *
     * @return the value of t_export_payment.return_status
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.return_status
     *
     * @param returnStatus the value for t_export_payment.return_status
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setReturnStatus(String returnStatus) {
        this.returnStatus = returnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.return_time
     *
     * @return the value of t_export_payment.return_time
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.return_time
     *
     * @param returnTime the value for t_export_payment.return_time
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.return_info
     *
     * @return the value of t_export_payment.return_info
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getReturnInfo() {
        return returnInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.return_info
     *
     * @param returnInfo the value for t_export_payment.return_info
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setReturnInfo(String returnInfo) {
        this.returnInfo = returnInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.return_guid
     *
     * @return the value of t_export_payment.return_guid
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getReturnGuid() {
        return returnGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.return_guid
     *
     * @param returnGuid the value for t_export_payment.return_guid
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setReturnGuid(String returnGuid) {
        this.returnGuid = returnGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.create_by
     *
     * @return the value of t_export_payment.create_by
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.create_by
     *
     * @param createBy the value for t_export_payment.create_by
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.create_time
     *
     * @return the value of t_export_payment.create_time
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.create_time
     *
     * @param createTime the value for t_export_payment.create_time
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.remark
     *
     * @return the value of t_export_payment.remark
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.remark
     *
     * @param remark the value for t_export_payment.remark
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.lastupdate_by
     *
     * @return the value of t_export_payment.lastupdate_by
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getLastupdateBy() {
        return lastupdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.lastupdate_by
     *
     * @param lastupdateBy the value for t_export_payment.lastupdate_by
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setLastupdateBy(String lastupdateBy) {
        this.lastupdateBy = lastupdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.lastupdate_date
     *
     * @return the value of t_export_payment.lastupdate_date
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public Date getLastupdateDate() {
        return lastupdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.lastupdate_date
     *
     * @param lastupdateDate the value for t_export_payment.lastupdate_date
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setLastupdateDate(Date lastupdateDate) {
        this.lastupdateDate = lastupdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.created_by_company
     *
     * @return the value of t_export_payment.created_by_company
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getCreatedByCompany() {
        return createdByCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.created_by_company
     *
     * @param createdByCompany the value for t_export_payment.created_by_company
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setCreatedByCompany(String createdByCompany) {
        this.createdByCompany = createdByCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.update_by_company
     *
     * @return the value of t_export_payment.update_by_company
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getUpdateByCompany() {
        return updateByCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.update_by_company
     *
     * @param updateByCompany the value for t_export_payment.update_by_company
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setUpdateByCompany(String updateByCompany) {
        this.updateByCompany = updateByCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.ebc_code
     *
     * @return the value of t_export_payment.ebc_code
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getEbcCode() {
        return ebcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.ebc_code
     *
     * @param ebcCode the value for t_export_payment.ebc_code
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setEbcCode(String ebcCode) {
        this.ebcCode = ebcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.ebc_name
     *
     * @return the value of t_export_payment.ebc_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getEbcName() {
        return ebcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.ebc_name
     *
     * @param ebcName the value for t_export_payment.ebc_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setEbcName(String ebcName) {
        this.ebcName = ebcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.created_by_name
     *
     * @return the value of t_export_payment.created_by_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.created_by_name
     *
     * @param createdByName the value for t_export_payment.created_by_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.created_company_name
     *
     * @return the value of t_export_payment.created_company_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getCreatedCompanyName() {
        return createdCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.created_company_name
     *
     * @param createdCompanyName the value for t_export_payment.created_company_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setCreatedCompanyName(String createdCompanyName) {
        this.createdCompanyName = createdCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.updated_by_name
     *
     * @return the value of t_export_payment.updated_by_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getUpdatedByName() {
        return updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.updated_by_name
     *
     * @param updatedByName the value for t_export_payment.updated_by_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setUpdatedByName(String updatedByName) {
        this.updatedByName = updatedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.updated_company_name
     *
     * @return the value of t_export_payment.updated_company_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getUpdatedCompanyName() {
        return updatedCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.updated_company_name
     *
     * @param updatedCompanyName the value for t_export_payment.updated_company_name
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setUpdatedCompanyName(String updatedCompanyName) {
        this.updatedCompanyName = updatedCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.enterprise_id
     *
     * @return the value of t_export_payment.enterprise_id
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.enterprise_id
     *
     * @param enterpriseId the value for t_export_payment.enterprise_id
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.ciq_return_status
     *
     * @return the value of t_export_payment.ciq_return_status
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getCiqReturnStatus() {
        return ciqReturnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.ciq_return_status
     *
     * @param ciqReturnStatus the value for t_export_payment.ciq_return_status
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setCiqReturnStatus(String ciqReturnStatus) {
        this.ciqReturnStatus = ciqReturnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_payment.ciq_return_info
     *
     * @return the value of t_export_payment.ciq_return_info
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public String getCiqReturnInfo() {
        return ciqReturnInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_payment.ciq_return_info
     *
     * @param ciqReturnInfo the value for t_export_payment.ciq_return_info
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    public void setCiqReturnInfo(String ciqReturnInfo) {
        this.ciqReturnInfo = ciqReturnInfo;
    }
}