package com.zhoufb.dao;

import com.zhoufb.model.db.ExportPayment;

public interface ExportPaymentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_payment
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_payment
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    int insert(ExportPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_payment
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    int insertSelective(ExportPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_payment
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    ExportPayment selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_payment
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    int updateByPrimaryKeySelective(ExportPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_payment
     *
     * @mbggenerated Tue Nov 28 17:32:38 CST 2017
     */
    int updateByPrimaryKey(ExportPayment record);
}